# .github/workflows/ci.yml
name: Java CI with Maven

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, firefox, edge]

    steps:
    # Step 1: Check out the repository
    - name: Check out repository
      uses: actions/checkout@v3

    # Step 2: Set up JDK 22
    - name: Set up JDK 22
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '22'

    # Step 3: Cache Maven dependencies
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven

    # Step 4: Set up WebDriverManager for browser (Chrome/Firefox)
    - name: Set up WebDriverManager
      run: |
        mvn dependency:resolve
        mvn compile

    # Step 5: Run the tests with Maven
    - name: Run tests
      run: mvn test -Dtestng.xml=src/test/resources/testng.xml

    # Step 6: Upload Allure results 
    - name: Allure Report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: allure-results
        path: allure-results/

    # Step 7: Save screenshots 
    - name: Upload screenshots
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: screenshots
        path: screenshots/
