name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Build with Maven (ignore failures)
        run: mvn clean install || true

      - name: Run tests (ignore failures)
        run: mvn test -Dtestng.xml=testng.xml || true

    


